### ISSUE TITLE
get data from firebase using python-ndn

### ISSUE THREAD

**Issue by radara09** [named-data/python-ndn#67]
I make a server to retrieve data from firebase realtime database
using the template from producer.py with some adjustment
but I got error 
```
Traceback (most recent call last):
  File "/home/ndn/py_ml/source/producer.py", line 18, in <module>
    app = NDNApp()
  File "/home/ndn/.local/lib/python3.10/site-packages/ndn/app.py", line 63, in __init__
    self.keychain = default_keychain(config['pib'], config['tpm'])
  File "/home/ndn/.local/lib/python3.10/site-packages/ndn/client_conf.py", line 106, in default_keychain
    pib = KeychainSqlite3(os.path.join(pib_loc, 'pib.db'), tpm)
  File "/home/ndn/.local/lib/python3.10/site-packages/ndn/security/keychain/keychain_sqlite3.py", line 474, in __init__
    cursor = self.conn.execute('SELECT tpm_locator FROM tpmInfo')
sqlite3.OperationalError: no such table: tpmInfo
```

I have tried running it on several versions of python and it still gives the same error

any recommendation to solve this 
thank you

**Comment by zjkmxy** [comment]
How did you create this database? If you create it using `ndnsec`, there should exist such table.
The table `tpmInfo` only has one row and one record `tpm_locator` specifying the location of TPM.
If you also put tpm into the firebase, you may want to write some code manually to load keys from TPM. In that case, you can put a dummy record in the table `tpmInfo`. `KeychainSqlite3` will fetch this row but not use it to create a real TPM.

**Comment by radara09** [comment]
I create the database configuration using the frequently used way using the key file.

I lack information on how to use ndnsec, maybe there is a reference about connecting database using ndnsec.
